import useUpdateNodeData from "@/hooks/useUpdateNodedata";

const ResponseForm = ({ node }) => {
  const updateNodeData = useUpdateNodeData();

  return (
    <div className="space-y-6 p-5">
      {/* Heading */}
      <div>
        <h2 className="text-lg font-semibold text-white">
          Response
        </h2>

        <p className="mt-1 text-sm text-[#A1A1AA]">
          Configure the final response node.
        </p>
      </div>

      {/* Node Name */}
      <div>
        <label className="mb-2 block text-sm font-medium text-white">
          Node Name
        </label>

        <input
          type="text"
          value={node?.data?.label || ""}
          onChange={(e) =>
            updateNodeData(node.id, {
              label: e.target.value,
            })
          }
          placeholder="Final Response"
          className="h-11 w-full rounded-xl border border-[#27272A] bg-[#111114] px-4 text-white outline-none transition focus:border-[#7C3AED]"
        />
      </div>

      {/* Info */}
      <div className="rounded-xl border border-[#10B981]/20 bg-[#10B981]/10 p-4">
        <p className="text-sm leading-6 text-[#A7F3D0]">
          This node returns the output generated by the previous node as the
          final response of the workflow.
        </p>
      </div>
    </div>
  );
};

export default ResponseForm;